spring.datasource.url=jdbc:mysql://turntable.proxy.rlwy.net:55920/railway
spring.datasource.username=root
spring.datasource.password=AdjjfOoEZGbAQDiGSTbVgOIJyPuNgDtY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}





cloudinary.cloud-name=dgz3b3l48

cloudinary.api-key=275887529924475

cloudinary.api-secret=tyAkZbFAGbjl9PM-4rpIYzmY3-U



spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akthecomrade@gmail.com
spring.mail.password=pcbjsgupyxgljrbz


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true